require("plugins/lazy") -- lazy plugin init
require("core/settings")
require("core/keymaps")
require("plugins/nvim-tree")
require("plugins/lualine")
require("plugins/nvim-treesitter")
require("plugins/mason")
require("plugins/nvim-cmp")
require("plugins/telescope")
require("plugins/null-ls")
require("plugins/gitsigns")
require("plugins/nvim-autopairs")
require("plugins/comment")
require("plugins/which-key")
require("plugins/dashboard-nvim")
